[package]
name = "neobrood"
version = "0.1.0"
edition = "2021"

[features]
default = ["framepacing", "inspector"]
framepacing = ["dep:bevy_framepace"]
inspector = ["dep:bevy-inspector-egui"]

[dependencies]
anyhow = "1.0"
bitflags = "2.4"
bevy_framepace = { version = "0.14", optional = true }
bevy-inspector-egui = { version = "0.22", optional = true }
byteorder = "1.5"
directories = "5.0"
memchr = "2.7"
mimalloc = { version = "0.1", optional = true, default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.bevy]
version = "0.12"
features = ["dds"]

[dependencies.bevy_ecs_tilemap]
git = "https://github.com/StarArawn/bevy_ecs_tilemap"
rev = "b08a5d997867d5e5a760e296dc38e435c6b268cc"

[dependencies.broodmap]
git = "https://github.com/ShieldBattery/broodmap.git"
rev = "366096b917834047184375777bd6c35976b4dec2"

[dev-dependencies]
claims = "0.7"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
