[package]
name = "neobrood"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitflags = "1.3"
bevy = "0.9"
bevy_ecs_tilemap = "0.9"
bevy_framepace = "0.11"
iyes_loopless = "0.9"

[dependencies.broodmap]
git = "https://github.com/ShieldBattery/broodmap.git"
rev = "1f002b1"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
