[package]
name = "neobrood"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bitflags = "1.3"
bevy_ecs_tilemap = "0.9"
bevy_framepace = "0.11"
byteorder = "1.4"
directories = "4.0"
iyes_loopless = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.bevy]
version = "0.9"
features = [
    "dds"
]

[dependencies.broodmap]
git = "https://github.com/ShieldBattery/broodmap.git"
rev = "5ffe11ca8df79ea2a643fa03a82da06288b3309b"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
