use std::ops::Index;

use bevy::ecs::component::Component;
use num_enum::{FromPrimitive, IntoPrimitive};

use crate::{
    gamedata::{Construct, CONSTRUCTS},
    races::Race,
};

/// Specifies the type (e.g. class) of a construct (i.e. marine, zergling, mineral field, etc.).
#[derive(Component, Debug, Clone, Copy, PartialEq, Eq, Hash, FromPrimitive, IntoPrimitive)]
#[repr(u16)]
pub enum ConstructTypeId {
    TerranMarine = 0,
    TerranGhost = 1,
    TerranVulture = 2,
    TerranGoliath = 3,
    TerranGoliathTurret = 4,
    TerranSiegeTank = 5,
    TerranSiegeTankTurret = 6,
    TerranScv = 7,
    TerranWraith = 8,
    TerranScienceVessel = 9,
    HeroGuiMontag = 10,
    TerranDropship = 11,
    TerranBattlecruiser = 12,
    TerranSpiderMine = 13,
    TerranNuclearMissile = 14,
    TerranCivilian = 15,
    HeroSarahKerrigan = 16,
    HeroAlanSchezar = 17,
    HeroAlanSchezarTurret = 18,
    HeroJimRaynorVulture = 19,
    HeroJimRaynorMarine = 20,
    HeroTomKazansky = 21,
    HeroMagellan = 22,
    HeroEdmundDuke = 23,
    HeroEdmundDukeTurret = 24,
    HeroEdmundDukeSieged = 25,
    HeroEdmundDukeSiegedTurret = 26,
    HeroArcturusMengsk = 27,
    HeroHyperion = 28,
    HeroNorad2 = 29,
    TerranSiegeTankSieged = 30,
    TerranSiegeTankSiegedTurret = 31,
    TerranFirebat = 32,
    SpellScannerSweep = 33,
    TerranMedic = 34,
    ZergLarva = 35,
    ZergEgg = 36,
    ZergZergling = 37,
    ZergHydralisk = 38,
    ZergUltralisk = 39,
    ZergBroodling = 40,
    ZergDrone = 41,
    ZergOverlord = 42,
    ZergMutalisk = 43,
    ZergGuardian = 44,
    ZergQueen = 45,
    ZergDefiler = 46,
    ZergScourge = 47,
    HeroTorrasque = 48,
    HeroMatriarch = 49,
    ZergInfestedTerran = 50,
    HeroInfestedKerrigan = 51,
    HeroUncleanOne = 52,
    HeroHunterKiller = 53,
    HeroDevouringOne = 54,
    HeroKukulzaMutalisk = 55,
    HeroKukulzaGuardian = 56,
    HeroYggdrasill = 57,
    TerranValkyrie = 58,
    ZergCocoon = 59,
    ProtossCorsair = 60,
    ProtossDarkTemplar = 61,
    ZergDevourer = 62,
    ProtossDarkArchon = 63,
    ProtossProbe = 64,
    ProtossZealot = 65,
    ProtossDragoon = 66,
    ProtossHighTemplar = 67,
    ProtossArchon = 68,
    ProtossShuttle = 69,
    ProtossScout = 70,
    ProtossArbiter = 71,
    ProtossCarrier = 72,
    ProtossInterceptor = 73,
    HeroDarkTemplar = 74,
    HeroZeratul = 75,
    HeroTassadarZeratulArchon = 76,
    HeroFenixZealot = 77,
    HeroFenixDragoon = 78,
    HeroTassadar = 79,
    HeroMojo = 80,
    HeroWarbringer = 81,
    HeroGanthritor = 82,
    ProtossReaver = 83,
    ProtossObserver = 84,
    ProtossScarab = 85,
    HeroDanimoth = 86,
    HeroAldaris = 87,
    HeroArtanis = 88,
    CritterRhynadon = 89,
    CritterBengalaas = 90,
    SpecialCargoShip = 91,
    SpecialMercenaryGunship = 92,
    CritterScantid = 93,
    CritterKakaru = 94,
    CritterRagnasaur = 95,
    CritterUrsadon = 96,
    ZergLurkerEgg = 97,
    HeroRaszagal = 98,
    HeroSamirDuran = 99,
    HeroAlexeiStukov = 100,
    SpecialMapRevealer = 101,
    HeroGerardDuGalle = 102,
    ZergLurker = 103,
    HeroInfestedDuran = 104,
    SpellDisruptionWeb = 105,
    TerranCommandCenter = 106,
    TerranComsatStation = 107,
    TerranNuclearSilo = 108,
    TerranSupplyDepot = 109,
    TerranRefinery = 110,
    TerranBarracks = 111,
    TerranAcademy = 112,
    TerranFactory = 113,
    TerranStarport = 114,
    TerranControlTower = 115,
    TerranScienceFacility = 116,
    TerranCovertOps = 117,
    TerranPhysicsLab = 118,
    UnusedTerran1 = 119,
    TerranMachineShop = 120,
    UnusedTerran2 = 121,
    TerranEngineeringBay = 122,
    TerranArmory = 123,
    TerranMissileTurret = 124,
    TerranBunker = 125,
    SpecialCrashedNorad2 = 126,
    SpecialIonCannon = 127,
    PowerupUrajCrystal = 128,
    PowerupKhalisCrystal = 129,
    ZergInfestedCommandCenter = 130,
    ZergHatchery = 131,
    ZergLair = 132,
    ZergHive = 133,
    ZergNydusCanal = 134,
    ZergHydraliskDen = 135,
    ZergDefilerMound = 136,
    ZergGreaterSpire = 137,
    ZergQueensNest = 138,
    ZergEvolutionChamber = 139,
    ZergUltraliskCavern = 140,
    ZergSpire = 141,
    ZergSpawningPool = 142,
    ZergCreepColony = 143,
    ZergSporeColony = 144,
    UnusedZerg1 = 145,
    ZergSunkenColony = 146,
    SpecialOvermindWithShell = 147,
    SpecialOvermind = 148,
    ZergExtractor = 149,
    SpecialMatureChrysalis = 150,
    SpecialCerebrate = 151,
    SpecialCerebrateDaggoth = 152,
    UnusedZerg2 = 153,
    ProtossNexus = 154,
    ProtossRoboticsFacility = 155,
    ProtossPylon = 156,
    ProtossAssimilator = 157,
    UnusedProtoss1 = 158,
    ProtossObservatory = 159,
    ProtossGateway = 160,
    UnusedProtoss2 = 161,
    ProtossPhotonCannon = 162,
    ProtossCitatdelOfAdun = 163,
    ProtossCyberneticsCore = 164,
    ProtossTemplarArchives = 165,
    ProtossForge = 166,
    ProtossStargate = 167,
    SpecialStasisCellPrison = 168,
    ProtossFleetBeacon = 169,
    ProtossArbiterTribunal = 170,
    ProtossRoboticsSupportBay = 171,
    ProtossShieldBattery = 172,
    SpecialKhaydarinCrystalForm = 173,
    SpecialProtossTemple = 174,
    SpecialXelNagaTemple = 175,
    ResourceMineralField1 = 176,
    ResourceMineralField2 = 177,
    ResourceMineralField3 = 178,
    UnusedCave = 179,
    UnusedCaveIn = 180,
    UnusedCantina = 181,
    UnusedMiningPlatform = 182,
    UnusedIndependentCommandCenter = 183,
    SpecialIndependentStarport = 184,
    UnusedIndependentJumpGate = 185,
    UnusedRuins = 186,
    UnusedKhaydarinCrystalFormation = 187,
    ResourceVespeneGeyser = 188,
    SpecialWarpGate = 189,
    SpecialPsiDisrupter = 190,
    UnusedZergMarker = 191,
    UnusedTerranMarker = 192,
    UnusedProtossMarker = 193,
    SpecialZergBeacon = 194,
    SpecialTerranBeacon = 195,
    SpecialProtossBeacon = 196,
    SpecialZergFlagBeacon = 197,
    SpecialTerranFlagBeacon = 198,
    SpecialProtossFlagBeacon = 199,
    SpecialPowerGenerator = 200,
    SpecialOvermindCocoon = 201,
    SpecialDarkSwarm = 202,
    SpecialFloorMissileTrap = 203,
    SpecialFloorHatch = 204,
    SpecialUpperLevelDoor = 205,
    SpecialRightUpperLevelDoor = 206,
    SpecialPitDoor = 207,
    SpecialRightPitDoor = 208,
    SpecialFloorGunTrap = 209,
    SpecialWallMissileTrap = 210,
    SpecialWallFlameTrap = 211,
    SpecialRightWallMissileTrap = 212,
    SpecialRightWallFlameTrap = 213,
    StartLocation = 214,
    PowerupFlag = 215,
    PowerupYoungChrysalis = 216,
    PowerupPsiEmitter = 217,
    PowerupDataDisk = 218,
    PowerupKhaydarinCrystal = 219,
    PowerupMineralCluster1 = 220,
    PowerupMineralCluster2 = 221,
    PowerupProtossGasOrb1 = 222,
    PowerupProtossGasOrb2 = 223,
    PowerupZergGasSac1 = 224,
    PowerupZergGasSac2 = 225,
    PowerupTerranGasTank1 = 226,
    PowerupTerranGasTank2 = 227,
    #[num_enum(catch_all)]
    Unknown(u16),
}

impl Race {
    /// Returns the [Construct] for this race's starting building.
    pub fn hq_building(&self) -> &'static Construct {
        match self {
            Race::Protoss => &CONSTRUCTS[ConstructTypeId::ProtossNexus],
            Race::Terran => &CONSTRUCTS[ConstructTypeId::TerranCommandCenter],
            Race::Zerg => &CONSTRUCTS[ConstructTypeId::ZergHatchery],
        }
    }
}

impl Index<ConstructTypeId> for [Construct; 228] {
    type Output = Construct;

    #[inline]
    fn index(&self, index: ConstructTypeId) -> &Self::Output {
        &self[u16::from(index) as usize]
    }
}

/// Component that specifies a [Construct]'s owner (via a player number).
#[derive(Component, Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct OwnedConstruct(pub u8);
